### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by onlyamessenger** [FrikkieSnyman/investec-tools#1]
Hi Frikkie,

Just a quick one, I don't see the transfer endpoints listed on the Programmable Banking API documentation page. Is this a bleeding edge feature not everyone has access to yet?

**Comment by FrikkieSnyman** [comment]
Hey @ascendedco 

Sorry I'm only replying now - I never received a notification for this.

Anyway, when I created this script, the transfer API was still in beta. In the meantime, it's been released, and I believe the documentation should be updated on investec's side already.
