### ISSUE TITLE
[Q] Minimum balance considerations

### ISSUE THREAD

**Issue by RemeJuan** [FrikkieSnyman/investec-tools#2]
Hi there,

Love what this script can do but I was wondering, and maybe I am overthinking things.

How would the minimum balance vs "debit order date" work, would it be viable to consider factoring that in (happy to do the work and PR).

My thinking says my general minimum is R2000, however on the first of the month medical, bond, car, life, etc all go off and depending on who you are that could run 10/20/30k maybe even more, in this case, one would definitely be tapping onto their facility, albeit for less than an hour.

Not sure if the bank would not charge interest for that or for the hour/day.

On that day or even an hour, the 2k is far less than 10k ensuring you would hit your facility.

Would it be worth adding optional ENV variables, an array for debit order dates (cause we can almost never get them to all be on the same date), and then an alternative minimum for those dates?

So something like 

```
if (arr.includes(new Date().getDate())) {
    minimumBalance = debitOrderMinimBalance;
}
```

Or something like that.

**Comment by FrikkieSnyman** [comment]
Hey @RemeJuan 

Yeah, I've been recently running into this exact same issue.

I've considered adding it exactly as you described, so if you have already created it, then please feel free to create a PR for it!
